# Generated by Django 5.1.7 on 2025-03-29 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
