# Generated by Django 5.1.7 on 2025-03-30 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
