# Generated by Django 5.1.7 on 2025-04-05 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Response',
        ),
    ]
